### ISSUE TITLE
config

### ISSUE THREAD

**Issue by liuly0322** [Tyh2001/vitepress-template#1]
https://github.com/Tyh2001/vitepress-template/blob/d3843ca7b126cbc4f6d4cee6a37099ce8b7a7231/docs/.vitepress/config.ts#L11-L13

这里需要加上 `lastUpdated: true,` 否则右下角不显示最近更新时间

[lastUpdated](https://vitepress.vuejs.org/config/app-configs#lastupdated)

**Comment by Tyh2001** [comment]
好的，晚上更新～

**Comment by Tyh2001** [comment]
> 

已修复
