### ISSUE TITLE
怎么自动提取每一个md的标题作为sildBar

### ISSUE THREAD

**Issue by didoee** [Tyh2001/vitepress-template#2]
怎么自动提取每一个md的标题作为sildBar

**Comment by Tyh2001** [comment]
> 如何自动提取每个 md 的标题作为 sildBar

sildBar 基本上都是直接写死的，保持和 md 标题一致就好了，参考 [这里](https://github.com/Tyh2001/vitepress-template/blob/master/docs/.vitepress/utils/sidebar.ts)

**Comment by didoee** [comment]
如果页面中的标题过多，直接这样写死的话，太繁琐

**Comment by Tyh2001** [comment]
> 如果页面中的标题过多，直接这样写死的话，太繁琐

据我所知，目前官方并没有相关 api，不过你可以尝试使用原生 dom 方法获取，因为一级标题会被渲染成为 h1 标签，可以尝试获取到 h1 的 innerHTML 的内容进行实现
