### ISSUE TITLE
适用的node版本

### ISSUE THREAD

**Issue by SuperYIP** [Tyh2001/vitepress-template#3]
博主使用的node版本是多少？

**Comment by Tyh2001** [comment]
> 博主使用的node版本是多少？

现在用的 v18.17.1，遇到什么问题了吗？

**Comment by SuperYIP** [comment]
安装依赖的时候提示could not resolve，目前用npm i --legacy-peer-deps先装上了

**Comment by Tyh2001** [comment]
> 安装依赖的时候提示could not resolve，目前用npm i --legacy-peer-deps先装上了

推荐使用 pnpm 安装
